# Generated by Django 3.1.5 on 2021-01-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210122_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delievered', 'Delievered')], default='pending', max_length=10),
        ),
    ]
